In [1]:
import os, sys
import django
import pytz
from dateutil import parser
from django.utils.timezone import make_aware
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
from edc_base.utils import age, get_utcnow
sys.path.append('../..') # add path to project root dir
os.environ["DJANGO_SETTINGS_MODULE"] = "esr21.settings"
import pandas as pd

# Connect to Django ORM
django.setup()
import uuid
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError

In [2]:
cvs = VaccinationDetails.objects.values_list('subject_visit__subject_identifier', 'adverse_event', 'site_id',
                                             'vaccination_site', 'received_dose_before')

In [4]:
from edc_base.utils import age, get_utcnow
final_data = [['pid', 'adverse_event', 'site_id', 'vaccination_site', 'dose_received', 'age', 'gender']]
for a in cvs:
    try:
        ic = InformedConsent.objects.get(subject_identifier=a[0])
    except InformedConsent.DoesNotExist:
        pass
    else:
        part_age = age(ic.dob, get_utcnow()) 
        if part_age:
            part_age=part_age.years
            a = list(a)
            a.append(part_age)
            final_data.append(a)
        a.append(ic.gender)

In [5]:
df_vc = pd.DataFrame(final_data)
df_vc

,0,1,2,3,4,5,6
0,pid,adverse_event,site_id,vaccination_site,dose_received,age,gender
1,150-040993363-5,No,40,BHP-PMH SITE,first_dose,18,M
2,150-041970873-8,No,41,BHP-Maun General Hospital,first_dose,29,M
3,150-043940518-2,No,43,Francistown Site,first_dose,28,F
4,150-044960075-6,No,44,BHP-SELEBI PHIKWE SITE,first_dose,46,F
...,...,...,...,...,...,...,...
8033,150-044960397-4,No,44,BHP SELIBE PHIKWE SITE,first_dose,19,M
8034,150-043940593-5,No,43,Francistown Site,first_dose,29,F
8035,150-040991118-5,No,40,BHP PMH site,first_dose,49,F
8036,150-040250001-9,No,40,BHP-PMH Site,second_dose,43,M
8037,150-040992891-6,No,40,bhp-pmh site,first_dose,21,M

In [10]:
data_path = '/Users/imosweu/Desktop/esr21_data/'

In [11]:
vaccination_details = 'vaccination_details.csv'
fpath = data_path + vaccination_details
df_vc.to_csv(fpath, sep='|', encoding='utf-8')

In [12]:
aes = AdverseEvent.objects.all().values_list('subject_visit__subject_identifier', 'experienced_ae',
                                            'site_id')

In [16]:
aes

<QuerySet [('150-043940976-2', 'No', 43), ('150-043940163-7', 'No', 43), ('150-042980097-0', 'No', 42), ('150-042980101-0', 'No', 42), ('150-043940964-8', 'No', 43), ('150-042980145-7', 'No', 42), ('150-040990541-9', 'No', 40), ('150-040140006-2', 'No', 40), ('150-042980251-3', 'No', 42), ('150-043940598-4', 'No', 43), ('150-042130007-8', 'No', 42), ('150-042980015-2', 'No', 42), ('150-044960160-6', 'No', 44), ('150-040990217-6', 'No', 40), ('150-044960367-7', 'No', 44), ('150-043940780-8', 'No', 43), ('150-043940618-0', 'No', 43), ('150-043940856-6', 'No', 43), ('150-043940511-7', 'No', 43), ('150-041970013-1', 'No', 41), '...(remaining elements truncated)...']>

In [19]:
from edc_base.utils import age, get_utcnow
aes_final_data = [['pid', 'experienced_ae', 'site_id', 'age', 'gender', 'ae_details']]
for a in aes:
    try:
        ic = InformedConsent.objects.get(subject_identifier=a[0])
    except InformedConsent.DoesNotExist:
        pass
    else:
        part_age = age(ic.dob, get_utcnow()) 
        if part_age:
            a = list(a)
            part_age=part_age.years
            a.append(part_age)
            aes_final_data.append(a)
        a.append(ic.gender)
        
    aers = AdverseEventRecord.objects.filter(adverse_event__subject_visit__subject_identifier=a[0]).values_list(
        'ae_details', flat=True)
    a.append(aers)

In [20]:
df_aes = pd.DataFrame(aes_final_data)
df_aes

                    0               1        2    3       4           5
0                 pid  experienced_ae  site_id  age  gender  ae_details
1     150-043940976-2              No       43   31       F          ()
2     150-043940163-7              No       43   33       M          ()
3     150-042980097-0              No       42   44       F          ()
4     150-042980101-0              No       42   40       M          ()
...               ...             ...      ...  ...     ...         ...
5667  150-043940262-7              No       43   22       F          ()
5668  150-040991095-5              No       40   45       M          ()
5669  150-044960330-5              No       44   21       F          ()
5670  150-040990146-7              No       40   41       F          ()
5671  150-042980255-4              No       42   30       M          ()

[5672 rows x 6 columns]

In [21]:
ae_details = 'ae_details.csv'
fpath = data_path + ae_details
df_vc.to_csv(fpath, sep='|', encoding='utf-8')